pipeline:
  build-dev:
    image: docker
    environment:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    commands:
      - ls
      - echo $DOCKER_PASSWORD | docker login --username "$DOCKER_USERNAME" --password-stdin index.docker.io
  linter:
    image: python:alpine
    commands:
      - echo "hey"