version: "3.4"

services:
  app:
    image: czea/effective-thesis:${IMAGE_TAG:?missingImageTag}
    env_file:
      - bin/${ENVIRONMENT:?missingEnvironment}.env
    volumes:
      - db-data:/usr/src/app/data/
      - static-data:/usr/src/app/static/
      - media-data:/usr/src/app/media/
  nginx:
    # Make sure that nginx reloads the newly obtained certificates.
    command: "/bin/sh -c 'envsubst \\$$ENV_PREFIX < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    environment:
      ENV_PREFIX: "${ENV_PREFIX}"
    volumes:
      - ./bin/nginx.conf:/etc/nginx/conf.d/nginx.template
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - static-data:/data/static/
      - media-data:/data/media/
  certbot:
    image: certbot/certbot
    # Check if certificate is up for renewal every 12 hours as recommended by
    # Let’s Encrypt.
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
volumes:
  db-data:
  static-data:
  media-data:

