version: "3.4"

services:
  app:
    build: .
    image: index.docker.io/czea/effective-thesis
    environment:
      PYTHONDONTWRITEBYTECODE: "no-write"
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost"
      DB_NAME: "dev-eacr.sqlite3"
      WAGTAIL_SITE_NAME: "localhost"

      # Needed on production
      # SENDGRID_API_KEY: ""
      # SECRET_KEY: ""
      # EMAIL_BACKEND: "sgbackend.SendGridBackend"
      # DISQUS_API_KEY: ""
    volumes:
      - .:/usr/src/app
      - db-data:/usr/src/app/data/
      - static-data:/usr/src/app/static/
      - media-data:/usr/src/app/media/
    entrypoint: ["/usr/src/app/bin/run.sh"]
    expose:
      - "8000"
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./bin/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-data:/data/static/
    depends_on:
      - app
    restart: unless-stopped
volumes:
  db-data:
  static-data:
  media-data: