version: "3.4"

services:
  app:
    image: czea/effective-thesis
    entrypoint: ["/usr/src/app/bin/run.sh"]
    expose:
      - "8000"
    restart: unless-stopped
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./bin/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped
