version: 2
jobs:
  build:
    environment:
      _BASE_IMAGE: czea/effective-thesis
      IMAGE_NAME: czea/effective-thesis:$CIRCLE_SHA1
      $LATEST_IMAGE: czea/effective-thesis:latest
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker pull $LATEST_IMAGE || exit 0
            docker build -t $LATEST_IMAGE --cache-from $LATEST_IMAGE .
            docker tag $LATEST_IMAGE $IMAGE_NAME
  publish-latest:
    environment:
      IMAGE_NAME: building-on-ci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME
            docker push $LATEST_IMAGE