version: 2
jobs:
  build:
    environment:
      LATEST_IMAGE: czea/effective-thesis:latest
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker pull $LATEST_IMAGE || exit 0
            docker build -t $LATEST_IMAGE --cache-from $LATEST_IMAGE .
            docker tag $LATEST_IMAGE czea/effective-thesis:$CIRCLE_SHA1
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push czea/effective-thesis:$CIRCLE_SHA1
            docker push $LATEST_IMAGE
      - run:
          name: Deploy Over SSH
          command: |
            ssh -o "StrictHostKeyChecking=no" dan@35.207.162.44 "ls"