# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-10 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesispage',
            name='date',
        ),
    ]
