# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 12:33
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0003_auto_20170610_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisindexpage',
            name='intro',
            field=wagtail.wagtailcore.fields.StreamField((('rawHtml', wagtail.wagtailcore.blocks.RawHTMLBlock()),)),
        ),
    ]
