# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0004_auto_20170611_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesispage',
            name='header',
        ),
    ]
