# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('theses', '0007_auto_20170717_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisprovider',
            name='name',
            field=models.CharField(default='Default Provider Name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thesisprovider',
            name='provider_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='thesisprovider',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
