# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0011_thesisindexpage_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisprovider',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
