# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0012_auto_20170806_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisprovider',
            name='link',
            field=models.URLField(default='efektivni-altruismus.cz'),
            preserve_default=False,
        ),
    ]
