# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('theses', '0015_auto_20170906_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisindexpage',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
