# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailmenus', '0021_auto_20170106_2352'),
        ('theses', '0016_thesisindexpage_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisprojectpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ThesisProjectPage',
        ),
    ]
