# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('theses', '0019_thesischoosehelppage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisDiscipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('taggit.tag',),
        ),
        migrations.AddField(
            model_name='thesispage',
            name='discipline',
            field=modelcluster.fields.ParentalManyToManyField(to='theses.ThesisDiscipline'),
        ),
    ]
