# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0020_auto_20171228_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisdiscipline',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='thesisprovider',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
