# Generated by Django 2.0.3 on 2018-09-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('theses', '0024_thesisfinishedindexpage_thesisfinishedpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisfinishedpage',
            name='pdf_thesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
