# Generated by Django 2.0.3 on 2018-09-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0025_thesisfinishedpage_pdf_thesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisfinishedpage',
            name='pdf_thesis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
