# Generated by Django 2.0.3 on 2018-09-02 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('theses', '0026_auto_20180902_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisfinishedpage',
            name='pdf_thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
