# Generated by Django 2.0.3 on 2018-09-02 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('theses', '0027_thesisfinishedpage_pdf_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisfinishedpage',
            name='about_author',
            field=models.CharField(default='These are few words about the author. He is brave and good, we generally like him although...', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thesisfinishedpage',
            name='author_pic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
