# Generated by Django 2.0.3 on 2018-09-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0028_auto_20180902_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisfinishedpage',
            name='intro',
        ),
    ]
