# Generated by Django 2.0.3 on 2018-09-06 16:58

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0029_remove_thesisfinishedpage_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisfinishedpage',
            name='about_author',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
