# Generated by Django 2.2.1 on 2020-08-31 06:49

from django.db import migrations
import theses.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0039_auto_20200831_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisdiscipline',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='thesisdiscipline',
            name='topics',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('heading_linkable', theses.models.HeadingBlock(features=['bold', 'italic', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'], help_text='heading text')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('rawHtml', wagtail.core.blocks.RawHTMLBlock())], blank=True, null=True),
        ),
    ]
