# Generated by Django 2.2.1 on 2021-10-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theses', '0042_submenuitem_submenupage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisfinishedpage',
            name='pdf_thesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
