# Generated by Django 2.2.1 on 2022-01-23 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('theses', '0043_auto_20211017_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesissimple',
            name='top_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='thesissimple',
            name='top_image_heading',
            field=models.CharField(blank=True, help_text='Text displayed over the image. It is applicable only if an image is selected.', max_length=255, null=True),
        ),
    ]
